export PATH="/home/amoda/Projects/wasm_asm_git/asm/emsdk_portable:/home/amoda/Projects/wasm_asm_git/asm/emsdk_portable/clang/e1.37.19_64bit:/home/amoda/Projects/wasm_asm_git/asm/emsdk_portable/node/4.1.1_64bit/bin:/home/amoda/Projects/wasm_asm_git/asm/emsdk_portable/emscripten/1.37.19:/home/amoda/bin:/home/amoda/.local/bin:/opt/maven/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin"
export EMSDK="/home/amoda/Projects/wasm_asm_git/asm/emsdk_portable"
export EM_CONFIG="/home/amoda/.emscripten"
export BINARYEN_ROOT="/home/amoda/Projects/wasm_asm_git/asm/emsdk_portable/clang/e1.37.19_64bit/binaryen"
export EMSCRIPTEN="/home/amoda/Projects/wasm_asm_git/asm/emsdk_portable/emscripten/1.37.19"
